import type { Metadata } from 'next';
import { Geist, Geist_Mono, Nunito } from 'next/font/google';
import './globals.css';
import Home from '@/components/layout/Home';
import Skills from '@/components/layout/Skills';
import Work from '@/components/layout/Work';
import Project from '@/components/layout/Project';

const nunito = Nunito({
    variable: '--font-nunito',
    subsets: ['latin'],
    weight: ['300', '400', '500', '600', '700'],
});

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

//Root Layout
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} ${nunito.variable} antialiased`}>
                <Home />
                <Skills />
                <Work />
                <Project />
                {children}
            </body>
        </html>
    );
}
