import type { Metadata } from 'next';
import { Geist, Geist_Mono, Nunito, Playwrite_AU_VIC, Poppins, Source_Code_Pro } from 'next/font/google';
import './globals.css';
import NavBar from '@/components/layout/NavBar';

const nunito = Nunito({
    variable: '--font-nunito',
    subsets: ['latin'],
    weight: ['300', '400', '500', '600', '700'],
});

const poppins = Poppins({
    variable: '--font-poppins',
    subsets: ['latin'],
    weight: ['300', '400', '500', '600', '700', '800', '900'],
});

const code = Source_Code_Pro({
    variable: '--font-code',
    subsets: ['latin'],
    weight: ['300', '400', '500', '600', '700', '800', '900'],
});

const playwriteAUVIC = Playwrite_AU_VIC({
    variable: '--font-playwrite',
    weight: ['400'],
});

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'My Profile',
    description: 'Generated by Nguyen Tuan',
};

//Root Layout
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${nunito.variable} ${playwriteAUVIC.variable} ${poppins.variable} ${code.variable} antialiased`}
            >
                <NavBar />
                {children}
            </body>
        </html>
    );
}
